### ISSUE TITLE
[ROS2] Deprecate `name` and `tree_root_name` in `create_move_to_tree`

### ISSUE THREAD

**Issue by egordon** [personalrobotics/ada_feeding#111]
As discussed in #102 

These can be gleaned directly from `self.blackboard.namespace` and `self.blackboard_tree_root.namespace`.

Additionally, we *should* be able to get rid of `self.blackboard_tree_root` entirely.

Proposal: `send_goal` and `get_result` will only be run in the root tree, so the distinction is unnecessary in those functions.

But `get_feedback` needs some introspection to work. This can be done with a Visitor.

It is generally bad BT design for a given sub-tree to be dependent on knowing the structure of its parent.

**Comment by amalnanavati** [comment]
I believe this is closed with #124 , right? At least, #124 handles deprecating `tree_root_name` and incorporating the visitor into `get_feedback`.  It doesn't deprecate `name` but I believe that is necessary (every tree should have a name).
